baseURL = "https://manilaworkshop.github.io/"
title = "IR for Climate Impact @ SIGIR 2025"
paginate = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "IR for Climate Impact @ SIGIR 2025"
description = "Workshop on Information Retrieval for Climate Impact at SIGIR 2025, July 17, 2025, Padova, Italy"
keywords = [
    "IR",
    "Climate Change",
    "SIGIR",
    "Workshop",
    "IPCC",
    "Climate Impact",
]
author = "Workshop Organizers"
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = false

showReadingTime = false
showShareButtons = false
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showRssButtonInSectionTermList = true
showToc = true

[params.assets]
disableHLJS = true
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[params.homeInfoParams]
Title = "MANILA25: IR for Climate Impact @ SIGIR 2025"
Content = """
Workshop on Information Retrieval for Climate Impact at SIGIR 2025.
July 17, 2025 | Padova, Italy

This workshop aims to bring together researchers and practitioners working at the
intersection of information retrieval and climate change.
"""

[[params.socialIcons]]
name = "Github"
url = "https://github.com/manilaworkshop"

[[params.socialIcons]]
name = "EasyChair"
url = "https://easychair.org/my/conference?conf=manila25"

[[menu.main]]
identifier = "submit"
name = "Submit"
url = "https://easychair.org/my/conference?conf=manila25"
weight = 10

[[menu.main]]
identifier = "sigir2025"
name = "SIGIR 2025"
url = "https://sigir2025.dei.unipd.it/"
weight = 20
